### PR TITLE
Improved handling of non-ideal messages, handle message header encoding

### PR DESCRIPTION
**Pull request by fastcat**
Here is more work I've added.  The older commits are mainly about managing degenerate cases and gracefully handling semi-invalid data.

The latest commit is to deal with a change in the GMail IMAP interface, where many GMail-added message headers are now put in UTF-8 encoding (e.g. "=?utf-8?q?blahblahblah?=") even if their values are entirely ASCII.  This was breaking some of the message indexing.

### CODE REVIEW

**Comment by hiciu** [comment]
Hello!

As you probably noticed, I'm not really maintaining this. Would you like to take over?

**Comment by fastcat** [comment]
Sure thing ... I'd forgotten this pull request was even still open :)

The code I'd had was working fine for me for a long time, until one of my accounts got so big that fetching the labels list for every message in the account in one go no longer worked -- Google was dropping the connection before it finished sending the full response most of the time, so I had to update it to work in batches.

**Comment by hiciu** [comment]
Thanks :). I've added you as a collaborator - feel free to edit README.md or other files as you see fit.

**Comment by fastcat** [comment]
Cheers!

**Pull request merged**
